### ISSUE TITLE
Postgres: Failed to process job: ERROR: more than one row returned by a subquery used as an expression

### ISSUE THREAD

**Issue by ffabreti** [SamSaffron/message_bus#104]
I have this config:
```
config   = Rails.configuration.database_configuration
    dbname = config[Rails.env]["database"]
    username = config[Rails.env]["username"]
    password = config[Rails.env]["password"]

    MessageBus.configure(
        backend: :postgres,
        backend_options: {
            user: username,
            password: password,
            dbname: dbname
        }
    )
```

I have edited `/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/backends/postgres.rb` to log to the console with this:
```
  def exec_prepared(conn, *a)
    #fer debug
    puts "EXEC_PREPARED: #{a}"
    r = conn.exec_prepared(*a)
    ...
```
console logs (original error is in portuguese):
```
Loading development environment (Rails 4.1.14)
Switch to inspect mode.
EXEC_PREPARED: ["insert_message", ["/__mb_keepalive__/", "{\"data\":16148,\"user_ids\":[-1],\"group_ids\":null,\"client_ids\":null}"]]
EXEC_PREPARED: ["publish", ["_message_bus_0", "1687|1687|/__mb_keepalive__/|{\"data\":16148,\"user_ids\":[-1],\"group_ids\":null,\"client_ids\":null}"]]
EXEC_PREPARED: ["expire", [604800]]
EXEC_PREPARED: ["clear_channel_backlog", ["/__mb_keepalive__/", 1687, 1000]]
Failed to process job: ERRO:  mais de um registro foi retornado por uma subconsulta utilizada como uma expressão 
 ["/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/backends/postgres.rb:131:in `exec_prepared'", "/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/backends/postgres.rb:131:in `exec_prepared'", "/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/backends/postgres.rb:45:in `block in clear_channel_backlog'", "/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/backends/postgres.rb:161:in `hold'", "/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/backends/postgres.rb:45:in `clear_channel_backlog'", "/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/backends/postgres.rb:265:in `publish'", "/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus.rb:233:in `publish'", "/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus.rb:433:in `block in new_subscriber_thread'", "/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/timer_thread.rb:98:in `call'", "/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/timer_thread.rb:98:in `do_work'", "/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/timer_thread.rb:29:in `block in initialize'"]
```

Any clues?

**Comment by jeremyevans** [comment]
This is definitely a bug.  I've added a pull request to fix it, as long as Travis doesn't complain, I'll merge it.
