### ISSUE TITLE
Errno::EPIPE message_bus/client.rb in write at line 156

### ISSUE THREAD

**Issue by cannikin** [SamSaffron/message_bus#146]
I see a lot of these in my logs...is this just the result of someone closing their browser or navigating away before MessageBus gets a chance to tell them something?

Ruby 2.4.1
Rails 5.1.2
Puma 3.8.2

```
Errno::EPIPE: Broken pipe
  from message_bus/client.rb:156:in `write'
  from message_bus/client.rb:156:in `write_headers'
  from message_bus/client.rb:175:in `write_chunk'
  from message_bus/client.rb:48:in `ensure_first_chunk_sent'
  from message_bus/rack/middleware.rb:149:in `block in call'
  from message_bus/client.rb:20:in `block in synchronize'
  from message_bus/client.rb:20:in `synchronize'
  from message_bus/client.rb:20:in `synchronize'
  from message_bus/rack/middleware.rb:146:in `call'
  from rack/session/abstract/id.rb:232:in `context'
  from rack/session/abstract/id.rb:226:in `call'
  from action_dispatch/middleware/cookies.rb:613:in `call'
  from action_dispatch/middleware/callbacks.rb:26:in `block in call'
  from active_support/callbacks.rb:97:in `run_callbacks'
  from action_dispatch/middleware/callbacks.rb:24:in `call'
  from action_dispatch/middleware/debug_exceptions.rb:59:in `call'
  from action_dispatch/middleware/show_exceptions.rb:31:in `call'
  from rails/rack/logger.rb:36:in `call_app'
  from rails/rack/logger.rb:24:in `block in call'
  from active_support/tagged_logging.rb:69:in `block in tagged'
  from active_support/tagged_logging.rb:26:in `tagged'
  from active_support/tagged_logging.rb:69:in `tagged'
  from rails/rack/logger.rb:24:in `call'
  from action_dispatch/middleware/remote_ip.rb:79:in `call'
  from request_store/middleware.rb:9:in `call'
  from action_dispatch/middleware/request_id.rb:25:in `call'
  from rack/method_override.rb:22:in `call'
  from rack/runtime.rb:22:in `call'
  from active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
  from action_dispatch/middleware/executor.rb:12:in `call'
  from rack/sendfile.rb:111:in `call'
  from action_dispatch/middleware/ssl.rb:66:in `call'
  from raven/integrations/rack.rb:50:in `call'
  from skylight/middleware.rb:61:in `call'
  from rails/engine.rb:522:in `call'
  from puma/configuration.rb:224:in `call'
  from puma/server.rb:600:in `handle_request'
  from puma/server.rb:435:in `process_client'
  from puma/server.rb:299:in `block in run'
  from puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by SamSaffron** [comment]
We recover just fine, I guess the question is if we should just swallow the
error or somehow check if the pipe is good prior to writing to it (which
still has timing problems)

**Comment by cannikin** [comment]
Okay so I'm pretty much safe to ignore this error in my exception notification app?

In the context of the gem I feel like it's safe to swallow if it's just expected behavior. Are there any instances where someone would want to catch and respond to this specifically? Maybe a config option to swallow the error?

**Comment by SamSaffron** [comment]
If you can do a PR that properly tests rude shutdown I am open to just
eating the error.

**Comment by cannikin** [comment]
Okay, I can trigger Errno::EPIPE by doing this in the client spec, but is it cheating?

```ruby
r,w = IO.pipe
@client.io = w
r.close
@client << MessageBus::Message.new(1, 1, '/test', 'test')
```

Which produces

```
Errno::EPIPE: Broken pipe
    /Users/rob/Sites/gems/message_bus/lib/message_bus/client.rb:156:in `write'
    /Users/rob/Sites/gems/message_bus/lib/message_bus/client.rb:156:in `write_headers'
    /Users/rob/Sites/gems/message_bus/lib/message_bus/client.rb:208:in `write_and_close'
    /Users/rob/Sites/gems/message_bus/lib/message_bus/client.rb:99:in `<<'
    spec/lib/message_bus/client_spec.rb:56:in `block (3 levels) in <top (required)>'
```

If that's okay then I'll get a PR up soon!

**Comment by cannikin** [comment]
Closing the write stream raises IOError instead:

```
IOError: closed stream
    /Users/rob/Sites/gems/message_bus/lib/message_bus/client.rb:156:in `write'
    /Users/rob/Sites/gems/message_bus/lib/message_bus/client.rb:156:in `write_headers'
    /Users/rob/Sites/gems/message_bus/lib/message_bus/client.rb:208:in `write_and_close'
    /Users/rob/Sites/gems/message_bus/lib/message_bus/client.rb:99:in `<<'
    spec/lib/message_bus/client_spec.rb:56:in `block (3 levels) in <top (required)>'
```

**Comment by cannikin** [comment]
PR #147 opened!

**Comment by cannikin** [comment]
Well I'm not seeing it occur in that place any more, but I'm seeing three instances of the error, all of them happening in `write_headers` which is the first place that tries to write to `@io`. It's being called outside of `<<`.

I'll work on another PR that catches it at the write_headers level instead.

**Comment by cannikin** [comment]
I think we fixed this with the README update, closing!
