### ISSUE TITLE
ActionDispatch::Flash shouldn't be required

### ISSUE THREAD

**Issue by arcreative** [SamSaffron/message_bus#24]
IMO, `app.middleware.insert_before(ActionDispatch::Flash, MessageBus::Rack::Middleware)` is a bit naïve since you don't know that the project will have it required.  In my rails-api project, it errors out: 

```
=> Booting WEBrick
=> Rails 4.1.8 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Notice: server is listening on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--binding option)
=> Ctrl-C to shutdown server
Exiting
/Users/adam/.rvm/gems/ruby-2.2.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/stack.rb:125:in `assert_index': No such middleware to insert before: ActionDispatch::Flash (RuntimeError)
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/stack.rb:88:in `insert'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/configuration.rb:68:in `block in merge_into'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/configuration.rb:67:in `each'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/configuration.rb:67:in `merge_into'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/engine.rb:497:in `app'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/application/finisher.rb:36:in `block in <module:Finisher>'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/initializable.rb:30:in `run'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/adam/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /Users/adam/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/adam/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/adam/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/adam/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/adam/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/adam/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/adam/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /Users/adam/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/application.rb:300:in `initialize!'
	from /Users/adam/repos/arcreative/hydrogen-api/config/environment.rb:5:in `<top (required)>'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `block in require'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
	from /Users/adam/repos/arcreative/hydrogen-api/config.ru:3:in `block in <main>'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
	from /Users/adam/repos/arcreative/hydrogen-api/config.ru:in `new'
	from /Users/adam/repos/arcreative/hydrogen-api/config.ru:in `<main>'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/rack-1.5.2/lib/rack/server.rb:277:in `build_app_and_options_from_config'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/rack-1.5.2/lib/rack/server.rb:199:in `app'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/commands/server.rb:50:in `app'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/rack-1.5.2/lib/rack/server.rb:314:in `wrapped_app'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/commands/server.rb:130:in `log_to_stdout'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/commands/server.rb:67:in `start'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:81:in `block in server'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:76:in `tap'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:76:in `server'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/adam/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by SamSaffron** [comment]
Sure, open to a patch here, the insertion point should be customisable,
message_bus runs fine under rack without rails and you should be allowed to
bypass the railstie if you want

https://github.com/SamSaffron/message_bus/blob/master/lib/message_bus/rails/railtie.rb


I think it would be bypassed if you require false and then insert it where
you want to.

**Comment by SamSaffron** [comment]
I think I just fixed this, try latest, if we fail to insert it after flash we just use it.
