### ISSUE TITLE
Problems running integration tests using message_bus

### ISSUE THREAD

**Issue by eiriklied** [SamSaffron/message_bus#44]
I just started using message_bus in a project and I really like it so far. Sometimes however when running feature specs in rspec, message_bus seems to kill the entire rspec process while the tests are running.

```
rspec
.................*.***............*................................F......*[1]    63130 killed     rspec
☁  myapp [master] ⚡ /Users/eiriklied/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/message_bus-1.0.16/lib/message_bus.rb:437:in `kill': No such process (Errno::ESRCH)
	from /Users/eiriklied/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/message_bus-1.0.16/lib/message_bus.rb:437:in `block (2 levels) in new_subscriber_thread'
	from /Users/eiriklied/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/message_bus-1.0.16/lib/message_bus.rb:434:in `fork'
	from /Users/eiriklied/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/message_bus-1.0.16/lib/message_bus.rb:434:in `block in new_subscriber_thread'
	from /Users/eiriklied/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/message_bus-1.0.16/lib/message_bus/timer_thread.rb:98:in `call'
	from /Users/eiriklied/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/message_bus-1.0.16/lib/message_bus/timer_thread.rb:98:in `do_work'
	from /Users/eiriklied/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/message_bus-1.0.16/lib/message_bus/timer_thread.rb:29:in `block in initialize'
```

In `log/test.log` I can also see `Global messages on 63130 timed out, restarting process` corresponding to https://github.com/SamSaffron/message_bus/blob/master/lib/message_bus.rb#L425

At other times I get failures like

```
Failures:

  1) team administration should allow for creating users through admin
     Failure/Error: visit team_admin_users_path
     SignalException:
       SIGTERM
     # ./spec/features/team_admin_spec.rb:14:in `block (2 levels) in <top (required)>'
```
along with 
```
☁  myapp [master] ⚡ /Users/eiriklied/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/message_bus-1.0.16/lib/message_bus.rb:437:in `kill': No such process (Errno::ESRCH)
	from /Users/eiriklied/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/message_bus-1.0.16/lib/message_bus.rb:437:in `block (2 levels) in new_subscriber_thread'
	from /Users/eiriklied/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/message_bus-1.0.16/lib/message_bus.rb:434:in `fork'
	from /Users/eiriklied/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/message_bus-1.0.16/lib/message_bus.rb:434:in `block in new_subscriber_thread'
	from /Users/eiriklied/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/message_bus-1.0.16/lib/message_bus/timer_thread.rb:98:in `call'
	from /Users/eiriklied/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/message_bus-1.0.16/lib/message_bus/timer_thread.rb:98:in `do_work'
	from /Users/eiriklied/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/message_bus-1.0.16/lib/message_bus/timer_thread.rb:29:in `block in initialize'
```

Any idea why this is happening?

**Comment by SamSaffron** [comment]
There are some really tricky tests that involve forking a ton of processes,
pretty sure they would be the thing that cause the issues. I really need
those tests, but may need to write a harness outside of rspec to run them
cause lots of magic lives in rspec.

also, I would like to port the tests to minitest if anyone feels like such
an adventure.

**Comment by eiriklied** [comment]
Sorry if I misunderstood something, but I'm not referring to the rspec tests for message_bus but my own test suite being killed when running tests after I started using the message_bus library in my application.

**Comment by SamSaffron** [comment]
ahh that ... you have a switch to disable it, it can happen due to
keepalive especially in test where you are constantly flushing redis.

see:

https://github.com/SamSaffron/message_bus/blob/master/lib/message_bus.rb#L338-L344

**Comment by eiriklied** [comment]
Awesome, it looks like that fixed it! Thanks so much for the quick response.
