### ISSUE TITLE
Seems error when working together puma

### ISSUE THREAD

**Issue by wjp2013** [SamSaffron/message_bus#45]
Got the warning.

```
[1324] Puma starting in cluster mode...
[1324] * Version 2.12.3 (ruby 2.2.1-p85), codename: Plutonian Photo Shoot
[1324] * Min threads: 16, max threads: 40
[1324] * Environment: production
[1324] * Process workers: 4
[1324] * Preloading application
[1324] * Listening on unix:///root/www_space/lenovo/shared/tmp/sockets/puma.sock
[1324] ! WARNING: Detected 2 Thread(s) started in app boot:
[1324] ! #<Thread:0x00000004c3dcd8@/root/www_space/lenovo/releases/6/vendor/bundle/ruby/2.2.0/gems/message_bus-1.0.16/lib/message_bus.rb:407 sleep> - /root/www_space/lenovo/releases/6/vendor/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/connection/ruby.rb:52:in `select'
[1324] ! #<Thread:0x00000004c3da80@/root/www_space/lenovo/releases/6/vendor/bundle/ruby/2.2.0/gems/message_bus-1.0.16/lib/message_bus/timer_thread.rb:29 sleep> - /root/www_space/lenovo/releases/6/vendor/bundle/ruby/2.2.0/gems/message_bus-1.0.16/lib/message_bus/timer_thread.rb:111:in `sleep'
[1324] * Daemonizing...
Connection to 123.57.172.249 closed.
       Elapsed time: 3.52 seconds
```

my puma config.

```
workers 4
threads 16, 40
#..... other configs

on_worker_boot do
  # Worker specific setup for Rails 4.1+
  # See: https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#on-worker-boot
  ActiveRecord::Base.establish_connection
  
  # Forking/threading app servers
  MessageBus.after_fork
end
```

- Ruby version ruby-2.2.1 [ x86_64 ]
- Rails 4.2.3
- Unbuntu 1404_64

**Comment by SamSaffron** [comment]
this was tested recently, the error about the extra thread is not really legit, message bus needs a couple of threads to manage long polling, @evanphx is there any way of whitelisting threads so puma will not complain about them?

**Comment by evanphx** [comment]
The warning is legit, they are started in the master process and are orphans since no user code runs there.

It's just a warning so users remember to restart those threads in the workers.
