### ISSUE TITLE
 undefined method `configure'

### ISSUE THREAD

**Issue by zeitnot** [SamSaffron/message_bus#81]
I am using rails 4.2.5. I have created an init file for message_bus and set ```ruby MessageBus.configure(backend: :memory)``` to that file. After this the following error is throwed. BTW I am using thin server.

/home/mehmet/apps/ruby/mbus/config/initializers/message_bus.rb:1:in `<top (required)>': undefined method `configure' for MessageBus:Module (NoMethodError)

**Comment by uri** [comment]
Yeah I'm getting the same thing but using redis as the backend.

**Comment by uri** [comment]
I was able to reproduce this in a new environemnt

```bash
$ rails --version
Rails 4.2.5.2
$ rails new -BJT mb_test
# Add gem 'message_bus' to Gemfile
$ bundle
# Add initializers according to readme
$ rails c
```

Here is what is provided in the README 

>Memory

>message_bus also supports an in-memory backend. This can be used for testing or simple single-process environments that do not require persistence.

>MessageBus.configure(backend: :memory)

Here is the error message it produces:

```
/Users/USER/Desktop/mb_test/config/initializers/message_bus.rb:1:in `<top (required)>': undefined method `configure' for MessageBus:Module (NoMethodError)
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `load'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `block in load'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `load'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/engine.rb:652:in `block in load_config_initializer'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:166:in `instrument'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/engine.rb:651:in `load_config_initializer'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/engine.rb:615:in `each'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/engine.rb:615:in `block in <class:Engine>'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `instance_exec'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `run'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:44:in `each'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:44:in `tsort_each_child'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:413:in `call'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `call'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:54:in `run_initializers'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/application.rb:352:in `initialize!'
        from /Users/USER/Desktop/mb_test/config/environment.rb:5:in `<top (required)>'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/application.rb:328:in `require'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/application.rb:328:in `require_environment!'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:67:in `console'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /Users/USER/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by uri** [comment]
The current version of the Gem is v1.1.1 what's visible on the README is the latest commit. To see the correct README, view a tag: https://github.com/SamSaffron/message_bus/tree/v1.1.1

**Comment by SamSaffron** [comment]
You are going to have to use the pre-release gem if you want the new configure API, we are going to do a new message bus stable release in a week, the situation where the docs are a bit too in the future is temporary.

**Comment by zeitnot** [comment]
@SamSaffron thanks, using the last commit solves the problem.
