### ISSUE TITLE
message_bus doesn't reconnect to postgres backend on database service restart

### ISSUE THREAD

**Issue by ffabreti** [SamSaffron/message_bus#92]
If  postgres service stops, message_bus cannot restablish the connection when postgres is restarted.  I guess it is not intended behaviour (bug).

tested with Rails and message_bus (2.0.0.beta)

how to reproduce:  (you need postgres up and running)
1. install and run [chat-example] (https://github.com/SamSaffron/message_bus/tree/master/examples/chat) and modify it's backend to postgres  or install [Rails message_bus-chat-example](https://github.com/ffabreti/message_bus-chat-example.git) 
2. start chat server
3. start browser client pointing to chat url
4. make sure chat is working
5. stop postgresql: (something like `systemctl stop postgresql-9.3` )
6. read the logs, message_bus tries to reconnect)
7. start postgresql: (something like `systemctl start postgresql-9.3` ) 
8. message_bus cannot reconnect

RAILS LOGs:
```
Started POST "/message-bus/8f767f541df341629d2c6c4a2067ee4c/poll" for 127.0.0.1 at 2016-04-13 15:15:15 -0300

PG::UnableToSend (no connection to the server
):
  message_bus (2.0.0.beta.6) lib/message_bus/backends/postgres.rb:129:in `exec_prepared'
  message_bus (2.0.0.beta.6) lib/message_bus/backends/postgres.rb:129:in `exec_prepared'
  message_bus (2.0.0.beta.6) lib/message_bus/backends/postgres.rb:55:in `block in backlog'
  message_bus (2.0.0.beta.6) lib/message_bus/backends/postgres.rb:159:in `hold'
  message_bus (2.0.0.beta.6) lib/message_bus/backends/postgres.rb:55:in `backlog'
  message_bus (2.0.0.beta.6) lib/message_bus/backends/postgres.rb:276:in `backlog'
  message_bus (2.0.0.beta.6) lib/message_bus.rb:286:in `backlog'
  message_bus (2.0.0.beta.6) lib/message_bus/client.rb:122:in `block in backlog'
  message_bus (2.0.0.beta.6) lib/message_bus/client.rb:120:in `each'
  message_bus (2.0.0.beta.6) lib/message_bus/client.rb:120:in `backlog'
  message_bus (2.0.0.beta.6) lib/message_bus/rack/middleware.rb:134:in `call'
  rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.15) lib/action_dispatch/middleware/cookies.rb:562:in `call'
  activerecord (4.1.15) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.15) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  activerecord (4.1.15) lib/active_record/migration.rb:380:in `call'
  actionpack (4.1.15) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.15) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.15) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.15) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.15) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  actionpack (4.1.15) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.15) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.15) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.15) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.15) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.15) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.15) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.15) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.1.15) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.5) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.15) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.15) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.15) lib/rails/engine.rb:514:in `call'
  railties (4.1.15) lib/rails/application.rb:144:in `call'
  rack (1.5.5) lib/rack/content_length.rb:14:in `call'
  puma (3.3.0) lib/puma/configuration.rb:224:in `call'
  puma (3.3.0) lib/puma/server.rb:561:in `handle_request'
  puma (3.3.0) lib/puma/server.rb:406:in `process_client'
  puma (3.3.0) lib/puma/server.rb:271:in `block in run'
  puma (3.3.0) lib/puma/thread_pool.rb:111:in `call'
  puma (3.3.0) lib/puma/thread_pool.rb:111:in `block in spawn_thread'

```

The logs point to the `rescue`clause on lib/message_bus/backends/postgres.rb `hold` method:
```
def hold
    current_pid = Process.pid
    if current_pid != @pid
      @pid = current_pid
      sync do
        INHERITED_CONNECTIONS.concat(@available)
        @available.clear
      end
    end

    if conn = sync{@allocated[Thread.current]}
      return yield(conn)
    end
      
    begin
      conn = sync{@available.shift} || new_pg_connection
      sync{@allocated[Thread.current] = conn}
      yield conn
    rescue PG::ConnectionBad => e
      # don't add this connection back to the pool
    ensure
      sync{@allocated.delete(Thread.current)}
      if Process.pid != current_pid
        sync{INHERITED_CONNECTIONS << conn}
      elsif conn && !e
        sync{@available << conn}
      end
    end
  end
```

I have tried something like: 
```
rescue PG::ConnectionBad => e
     client.reconnect
     retry
```
without success

**Comment by jeremyevans** [comment]
I guess we should be rescuing PG::UnableToSend in addition to PG::ConnectionBad, let me put together a patch for that.

**Comment by jeremyevans** [comment]
This looks like it closed automatically.  I think it should fix the problem, but can you test and confirm.  If it doesn't, I'll reopen.

**Comment by ffabreti** [comment]
No good, unfortunately.

Now it throws:
```
NoMethodError (undefined method `map!' for nil:NilClass):
  message_bus (2.0.0.beta.6) lib/message_bus/backends/postgres.rb:276:in `backlog'
  message_bus (2.0.0.beta.6) lib/message_bus.rb:286:in `backlog'
  message_bus (2.0.0.beta.6) lib/message_bus/client.rb:122:in `block in backlog'
  message_bus (2.0.0.beta.6) lib/message_bus/client.rb:120:in `each'
  message_bus (2.0.0.beta.6) lib/message_bus/client.rb:120:in `backlog'
  message_bus (2.0.0.beta.6) lib/message_bus/rack/middleware.rb:134:in `call'
  rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.15) lib/action_dispatch/middleware/cookies.rb:562:in `call'
  activerecord (4.1.15) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.15) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  activerecord (4.1.15) lib/active_record/migration.rb:380:in `call'
  actionpack (4.1.15) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.15) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.15) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.15) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.15) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  actionpack (4.1.15) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.15) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.15) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.15) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.15) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.15) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.15) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.15) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.1.15) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.5) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.15) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.15) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.15) lib/rails/engine.rb:514:in `call'
  railties (4.1.15) lib/rails/application.rb:144:in `call'
  rack (1.5.5) lib/rack/content_length.rb:14:in `call'
  puma (3.3.0) lib/puma/configuration.rb:224:in `call'
  puma (3.3.0) lib/puma/server.rb:561:in `handle_request'
  puma (3.3.0) lib/puma/server.rb:406:in `process_client'
  puma (3.3.0) lib/puma/server.rb:271:in `block in run'
  puma (3.3.0) lib/puma/thread_pool.rb:111:in `call'
  puma (3.3.0) lib/puma/thread_pool.rb:111:in `block in spawn_thread'
```
code affected:
```
def backlog(channel, last_id = nil)
    items = client.backlog channel, last_id.to_i

    items.map! do |id, data|
      MessageBus::Message.new id, id, channel, data
    end
  end

```

**Comment by jeremyevans** [comment]
Reopening.  That error should hopefully be simple to fix.

**Comment by jeremyevans** [comment]
OK, I've committed a possible fix for this issue, can you test and see if it improves things?

**Comment by ffabreti** [comment]
Thanks. will test your commit. 

Meanwhile I have done this below
(**and it works**, but trust me: I don't exactly know what I am doing !!!):

backends/postres.rb:
```
def hold
    ...
      
    begin
      ...
    rescue PG::ConnectionBad, PG::UnableToSend => e
        client.reconnect
        retry
    ensure
      ...
    end
  end
```

**stopped postgres** and rails kept throwing:
```
W, [2016-04-13T19:05:36.342075 #2219]  WARN -- : could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
 subscribe failed, reconnecting in 1 second. Call stack
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/message_bus-2.0.0.beta.6/lib/message_bus/backends/postgres.rb:175:in `initialize'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/message_bus-2.0.0.beta.6/lib/message_bus/backends/postgres.rb:175:in `new'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/message_bus-2.0.0.beta.6/lib/message_bus/backends/postgres.rb:175:in `raw_pg_connection'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/message_bus-2.0.0.beta.6/lib/message_bus/backends/postgres.rb:107:in `subscribe'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/message_bus-2.0.0.beta.6/lib/message_bus/backends/postgres.rb:334:in `global_subscribe'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/message_bus-2.0.0.beta.6/lib/message_bus.rb:469:in `global_subscribe_thread'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/message_bus-2.0.0.beta.6/lib/message_bus.rb:421:in `block in new_subscriber_thread'
```

**restarted postgres** and got some errors like:
```
Started POST "/message-bus/8f767f541df341629d2c6c4a2067ee4c/poll" for 127.0.0.1 at 2016-04-13 19:06:52 -0300

NameError (undefined local variable or method `client' for #<MessageBus::Postgres::Client:0x00000001ffbe68>):
  message_bus (2.0.0.beta.6) lib/message_bus/backends/postgres.rb:162:in `rescue in hold'
  message_bus (2.0.0.beta.6) lib/message_bus/backends/postgres.rb:171:in `hold'
  message_bus (2.0.0.beta.6) lib/message_bus/backends/postgres.rb:55:in `backlog'
```

and then **it got stable**:
```
Started POST "/message" for 127.0.0.1 at 2016-04-13 19:08:17 -0300
Processing by ChatRoomsController#message as */*
  Parameters: {"data"=>"jeeessus", "username"=>"joana"}
  Rendered text template (0.1ms)
Completed 200 OK in 9ms (Views: 1.4ms | ActiveRecord: 0.0ms)
```

**Comment by ffabreti** [comment]
@jeremyevans: your last commit works like a charm! Thanks.
