### ISSUE TITLE
errors on wrk benchmark

### ISSUE THREAD

**Issue by ffabreti** [SamSaffron/message_bus#95]
I have been testing a chat example using provided `wrk` sample in  `/message_bus/examples/bench`
I am not sure why errors are thrown, maybe it is expected behaviour, I hope I am missing something.
Maybe a config problem, or something misconfigured.

Test command:
```
$ wrk -c200 -d10s --timeout=30s -s bench.lua http://10.5.5.102:3000
```
After each test run, I see more and more errors:

Test results:
First run:
```
Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.58s   809.90ms   2.11s    77.63%
    Req/Sec   303.27    257.28     1.03k    57.69%
  1006 requests in 10.03s, 330.37KB read
  Socket errors: connect 0, read 19, write 0, timeout 0
  Non-2xx or 3xx responses: 5
```
Second run:
```
Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.61s   804.70ms   2.14s    78.71%
    Req/Sec   336.38    343.80     1.38k    88.46%
  1010 requests in 10.03s, 330.54KB read
  Socket errors: connect 0, read 5, write 0, timeout 0
  Non-2xx or 3xx responses: 74
```
Third run:
```
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.45s   903.20ms   2.17s    71.26%
    Req/Sec   402.61    424.53     1.44k    86.96%
  1110 requests in 10.03s, 361.54KB read
  Socket errors: connect 0, read 9, write 0, timeout 0
  Non-2xx or 3xx responses: 173
```
and lots of these on logs:

>
> 2016/04/15 15:48:35 [error] 921#0: *252 connect() to /tmp/passenger.1.0.901/generation-0/request failed (11: Resource temporarily unavailable) while connecting to upstream, client: 10.5.5.102, server: _, request: "POST /message-bus/a7dbce357bace4c170951b32b389648e/poll HTTP/1.1", upstream: "passenger:/tmp/passenger.1.0.901/generation-0/request:", host: "10.5.5.102:3000"
> 
> 2016/04/15 15:55:01 [error] 2020#0: *1474 upstream prematurely closed connection while reading response header from upstream, client: 10.5.5.102, server: _, request: "POST /message-bus/3e8c9c62ffcba06fed52c35b9ca83aed/poll HTTP/1.1", upstream: "passenger:/tmp/passenger.1.0.1991/generation-0/request:", host: "10.5.5.102:3000"`
>
> App 2041 stdout: W, [2016-04-15T15:55:16.179356 #2041]  WARN -- : PQconsumeInput()  subscribe failed, reconnecting in 1 second. Call stack
> App 2041 stdout: /home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-98a71c19be42/lib/message_bus/backends/postgres.rb:111:in `wait_for_notify'
> App 2041 stdout: /home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-98a71c19be42/lib/message_bus/backends/postgres.rb:111:in `subscribe'
> 

**Would that be normal within a test scenario where bursts are large and concentrated?
Is there something I can configure so things run smoothly?**

My env:

config.ru:
```
require 'message_bus'

require ::File.expand_path('../config/environment', __FILE__)

    if defined?(PhusionPassenger)
        # https://www.phusionpassenger.com/library/config/apache/tuning_sse_and_websockets/
        # https://github.com/dimelo/passenger-faye-issue

        PhusionPassenger.advertised_concurrency_level = 0

        # https://github.com/SamSaffron/message_bus
        PhusionPassenger.on_event(:starting_worker_process) do |forked|
            if forked
                # We're in smart spawning mode.
                MessageBus.after_fork
            else
                # We're in conservative spawning mode. We don't need to do anything.
            end
        end
    end

MessageBus.long_polling_interval = 1000 * 2
MessageBus.max_active_clients = 10000
use MessageBus::Rack::Middleware

run Rails.application
```
database.yml:
```
default: &default
  adapter: postgresql
  pool: 200
```
initializers/chat.rb:
```
MessageBus.configure(
    backend: :postgres,
    backend_options: {
        user: 'messagebus-chat',
        password: '123456',
        dbname: 'farma-chat_development'
    }
)
```

**Comment by SamSaffron** [comment]
Can you try testing this under unicorn or thin or puma to see if this is a passenger specific issue?

**Comment by ffabreti** [comment]
Yeah.
I've created an environment called `fake_production`:
```
# use this env for thread-safe tests

Rails.application.configure do

  config.cache_classes = true
  config.eager_load = true
  config.consider_all_requests_local       = false
  config.action_controller.perform_caching = true
  config.serve_static_assets = true
  config.assets.compile = true
  config.assets.digest = false
  config.assets.version = '1.0'
  config.assets.debug = true
  config.log_level = :info
  config.i18n.fallbacks = true

  config.active_support.deprecation = :notify
  config.log_formatter = ::Logger::Formatter.new
  config.active_record.dump_schema_after_migration = false
end
```
And config/puma/fake_production.rb:
```
#!/usr/bin/env puma
threads 1,20
workers 2
# preload_app!
require 'message_bus'
on_worker_boot do
  MessageBus.after_fork
  Rails.logger.info '========= ON WORKER BOOT =============='
end
```

Errors seen:
```
2016-04-22 11:20:03 -0300: Rack app error: #<Errno::EPIPE: Broken pipe>
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/client.rb:160:in `write'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/client.rb:160:in `block in write_headers'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/client.rb:157:in `each'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/client.rb:157:in `write_headers'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/client.rb:175:in `write_chunk'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/client.rb:48:in `ensure_first_chunk_sent'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/rack/middleware.rb:148:in `block in call'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/client.rb:20:in `block in synchronize'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/client.rb:20:in `synchronize'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/client.rb:20:in `synchronize'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/rack/middleware.rb:145:in `call'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/rack-1.5.5/lib/rack/content_length.rb:14:in `call'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/puma-3.4.0/lib/puma/configuration.rb:224:in `call'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/puma-3.4.0/lib/puma/server.rb:569:in `handle_request'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/puma-3.4.0/lib/puma/server.rb:406:in `process_client'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/puma-3.4.0/lib/puma/server.rb:271:in `block in run'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/puma-3.4.0/lib/puma/thread_pool.rb:114:in `call'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/puma-3.4.0/lib/puma/thread_pool.rb:114:in `block in spawn_thread'
2016-04-22 11:20:03 -0300: Rack app error: #<Errno::EPIPE: Broken pipe>
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/client.rb:159:in `write'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/client.rb:159:in `block in write_headers'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/client.rb:157:in `each'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/client.rb:157:in `write_headers'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/client.rb:175:in `write_chunk'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/client.rb:48:in `ensure_first_chunk_sent'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/rack/middleware.rb:148:in `block in call'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/client.rb:20:in `block in synchronize'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/client.rb:20:in `synchronize'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/client.rb:20:in `synchronize'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/rack/middleware.rb:145:in `call'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/rack-1.5.5/lib/rack/content_length.rb:14:in `call'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/puma-3.4.0/lib/puma/configuration.rb:224:in `call'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/puma-3.4.0/lib/puma/server.rb:569:in `handle_request'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/puma-3.4.0/lib/puma/server.rb:406:in `process_client'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/puma-3.4.0/lib/puma/server.rb:271:in `block in run'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/puma-3.4.0/lib/puma/thread_pool.rb:114:in `call'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/puma-3.4.0/lib/puma/thread_pool.rb:114:in `block in spawn_thread'
2016-04-22 11:20:03 -0300: Rack app error: #<NoMethodError: undefined method `write' for nil:NilClass>
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/client.rb:160:in `block in write_headers'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/client.rb:157:in `each'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/client.rb:157:in `write_headers'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/client.rb:175:in `write_chunk'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/client.rb:48:in `ensure_first_chunk_sent'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/rack/middleware.rb:148:in `block in call'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/client.rb:20:in `block in synchronize'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/client.rb:20:in `synchronize'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/client.rb:20:in `synchronize'
/home/fer/.rvm/gems/ruby-2.0.0-p451/bundler/gems/message_bus-a92e31f275f0/lib/message_bus/rack/middleware.rb:145:in `call'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/rack-1.5.5/lib/rack/content_length.rb:14:in `call'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/puma-3.4.0/lib/puma/configuration.rb:224:in `call'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/puma-3.4.0/lib/puma/server.rb:569:in `handle_request'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/puma-3.4.0/lib/puma/server.rb:406:in `process_client'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/puma-3.4.0/lib/puma/server.rb:271:in `block in run'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/puma-3.4.0/lib/puma/thread_pool.rb:114:in `call'
/home/fer/.rvm/gems/ruby-2.0.0-p451/gems/puma-3.4.0/lib/puma/thread_pool.rb:114:in `block in spawn_thread'
```

**Comment by SamSaffron** [comment]
hmmm I wonder if wrk is respecting the close after reqs, will try it out on local thanks for the details.

**Comment by SamSaffron** [comment]
I clarified and corrected what can be corrected here:

https://github.com/SamSaffron/message_bus/commit/460e5e05bcecb951fdc8152436ae5e369b146d71

**Comment by ffabreti** [comment]
Thanks. Explanations of how things work are essential :)

Have retested with great results:
```
$  wrk -c200 -d10s --timeout=30s -s bench.lua http://10.5.5.102:3000
Running 10s test @ http://10.5.5.102:3000
  2 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.75s   601.10ms   2.33s    85.04%
    Req/Sec   156.34    142.11   404.00     42.00%
  936 requests in 10.03s, 171.84KB read
Requests/sec:     93.35
Transfer/sec:     17.14KB

  921 requests in 10.03s, 169.09KB read
Requests/sec:     91.85
Transfer/sec:     16.86KB

  941 requests in 10.04s, 172.76KB read
Requests/sec:     93.77
Transfer/sec:     17.22KB

  920 requests in 10.03s, 169.06KB read
  Socket errors: connect 0, read 2, write 0, timeout 0
Requests/sec:     91.74
Transfer/sec:     16.86KB

  894 requests in 10.04s, 164.13KB read
Requests/sec:     89.02
Transfer/sec:     16.34KB

  930 requests in 10.03s, 170.74KB read
Requests/sec:     92.75
Transfer/sec:     17.03KB

  948 requests in 10.03s, 174.05KB read
Requests/sec:     94.52
Transfer/sec:     17.35KB

  899 requests in 10.03s, 165.12KB read
  Socket errors: connect 0, read 1, write 0, timeout 0
Requests/sec:     89.65
Transfer/sec:     16.47KB
```
Although wrk shows read errors, none were found on server console

if pushed to 1000 connections and 30s:
```
$  wrk -c1000 -d30s --timeout=30s -s bench.lua http://10.5.5.102:3000
Running 30s test @ http://10.5.5.102:3000
  2 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.97s   281.38ms   2.55s    90.46%
    Req/Sec   377.91    278.63     1.28k    65.25%
  13783 requests in 30.08s, 2.48MB read
  Socket errors: connect 0, read 134, write 0, timeout 0
Requests/sec:    458.27
Transfer/sec:     84.57KB
```
Those 134 read errors don't appear on server console
